name: Backpack
version: ${project.version}
main: me.iloveeatmuffin.backpack.Backpack
api-version: 1.13
authors: [ILoveEatMuffin]
commands:
  backpack:
    description: 背包owob
    usage: /<command>
    aliases:
      - bp
      //public void saveItem(ConfigurationSection section, ItemStack itemStack) {
      section.set("type", itemStack.getType().name());
      section.set("amount", itemStack.getAmount());

  }

    public ItemStack loadItem(ConfigurationSection section) {
    return new ItemStack(Material.valueOf(section.getString("type")), section.getInt("amount"));

  }

